export const products = [
  {
    id: 1,
    name: "Product 1",
    price: 19.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 1",
  },
  {
    id: 2,
    name: "Product 2",
    price: 29.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 2",
  },
  {
    id: 3,
    name: "Product 3",
    price: 29.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 3",
  },
  {
    id: 4,
    name: "Product 4",
    price: 29.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 4",
  },
  {
    id: 5,
    name: "Product 5",
    price: 29.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 5",
  },
  {
    id: 6,
    name: "Product 6",
    price: 29.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 6",
  },
  {
    id: 7,
    name: "Product 7",
    price: 39.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 7",
  },
  {
    id: 8,
    name: "Product 8",
    price: 49.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 8",
  },
  {
    id: 9,
    name: "Product 9",
    price: 39.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 9",
  },
  {
    id: 10,
    name: "Product 10",
    price: 49.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 10",
  },
  {
    id: 11,
    name: "Product 11",
    price: 59.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 11",
  },
  {
    id: 12,
    name: "Product 12",
    price: 39.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 12",
  },
  {
    id: 13,
    name: "Product 13",
    price: 69.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 13",
  },
  {
    id: 14,
    name: "Product 14",
    price: 79.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 14",
  },
  {
    id: 15,
    name: "Product 15",
    price: 49.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 15",
  },
  {
    id: 16,
    name: "Product 16",
    price: 59.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 16",
  },
  {
    id: 17,
    name: "Product 17",
    price: 89.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 17",
  },
  {
    id: 18,
    name: "Product 18",
    price: 69.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 18",
  },
  {
    id: 19,
    name: "Product 19",
    price: 99.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 19",
  },
  {
    id: 20,
    name: "Product 20",
    price: 79.99,
    imageUrl: "https://via.placeholder.com/150",
    description: "Description of Product 20",
  },
];
